on:
  push:
    branches: master

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::plyr
            any::plotly
            any::ggbump
            any::formattable
            any::ggrepel
            
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("fpl_lite_data_updater.R")'
        
      - name: Update Dashboard
        run: Rscript -e "rmarkdown::render('docs/index.Rmd')"

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/data/1_gw_weekly_scores.RDS
          git add docs/data/2_participant_team_df.RDS
          git add docs/data/2_fpl_player_stats_2324.RDS
          git add docs/data/3_chip_tracker.RDS
          git add docs/data/4_fpl_transfers.RDS
          git add docs/index.Rmd
          git add docs/index.html
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin master || echo "No changes to commit"
